// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {box} from '../models';

export function CancelImportMod(arg1:string):Promise<void>;

export function ImportMod():Promise<box.ImportMod>;

export function Open():Promise<box.Settings>;

export function SetSettings(arg1:box.Settings):Promise<void>;

export function Settings():Promise<box.Settings>;

export function StartImportMod(arg1:box.ImportMod):Promise<string>;

export function StopSyncSteamMods(arg1:string):Promise<void>;

export function SyncSteamMods():Promise<string>;
