// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelImportMod(arg1) {
  return window['go']['box']['Box']['CancelImportMod'](arg1);
}

export function ImportMod() {
  return window['go']['box']['Box']['ImportMod']();
}

export function Open() {
  return window['go']['box']['Box']['Open']();
}

export function SetSettings(arg1) {
  return window['go']['box']['Box']['SetSettings'](arg1);
}

export function Settings() {
  return window['go']['box']['Box']['Settings']();
}

export function StartImportMod(arg1) {
  return window['go']['box']['Box']['StartImportMod'](arg1);
}

export function StopSyncSteamMods(arg1) {
  return window['go']['box']['Box']['StopSyncSteamMods'](arg1);
}

export function SyncSteamMods() {
  return window['go']['box']['Box']['SyncSteamMods']();
}
