// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {box} from '../models';

export function ExistsModule(arg1:string):Promise<boolean>;

export function GetImage(arg1:string):Promise<string>;

export function GetModule(arg1:string):Promise<box.Module>;

export function ImportModules(arg1:box.ImportPlan):Promise<Array<box.Module>>;

export function ListModuleByTitle(arg1:string):Promise<Array<box.Module>>;

export function ListWorkshopModules():Promise<Array<box.WorkshopModule>>;

export function MakeModuleImportPlan(arg1:box.MakeModuleImportPlanParam):Promise<box.ImportPlan>;

export function Open():Promise<box.Settings>;

export function Settings():Promise<box.Settings>;

export function StopSyncWorkshopMods(arg1:string):Promise<void>;

export function SyncWorkshopMods():Promise<string>;

export function UpdateSettings(arg1:box.Settings):Promise<void>;
