// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CancelImportMod(arg1) {
  return window['go']['box']['Box']['CancelImportMod'](arg1);
}

export function GetImage(arg1) {
  return window['go']['box']['Box']['GetImage'](arg1);
}

export function ImportMod() {
  return window['go']['box']['Box']['ImportMod']();
}

export function ListWorkshopModules() {
  return window['go']['box']['Box']['ListWorkshopModules']();
}

export function Module(arg1) {
  return window['go']['box']['Box']['Module'](arg1);
}

export function Open() {
  return window['go']['box']['Box']['Open']();
}

export function Settings() {
  return window['go']['box']['Box']['Settings']();
}

export function StartImportMod(arg1) {
  return window['go']['box']['Box']['StartImportMod'](arg1);
}

export function StopSyncWorkshopMods(arg1) {
  return window['go']['box']['Box']['StopSyncWorkshopMods'](arg1);
}

export function SyncWorkshopMods() {
  return window['go']['box']['Box']['SyncWorkshopMods']();
}

export function UpdateSettings(arg1) {
  return window['go']['box']['Box']['UpdateSettings'](arg1);
}
