// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetImage(arg1) {
  return window['go']['box']['Box']['GetImage'](arg1);
}

export function GetModule(arg1) {
  return window['go']['box']['Box']['GetModule'](arg1);
}

export function ImportModules(arg1) {
  return window['go']['box']['Box']['ImportModules'](arg1);
}

export function ListWorkshopModules() {
  return window['go']['box']['Box']['ListWorkshopModules']();
}

export function MakeModuleImportPlan(arg1) {
  return window['go']['box']['Box']['MakeModuleImportPlan'](arg1);
}

export function Open() {
  return window['go']['box']['Box']['Open']();
}

export function Settings() {
  return window['go']['box']['Box']['Settings']();
}

export function StopSyncWorkshopMods(arg1) {
  return window['go']['box']['Box']['StopSyncWorkshopMods'](arg1);
}

export function SyncWorkshopMods() {
  return window['go']['box']['Box']['SyncWorkshopMods']();
}

export function UpdateSettings(arg1) {
  return window['go']['box']['Box']['UpdateSettings'](arg1);
}
